import { Vazirmatn } from "next/font/google";
import "./globals.css";
import Navbar from "../components/layout/Navbar"
import Footer from "../components/layout/Footer"
import Modal from "@/components/layout/Modal";

const vazirmatn = Vazirmatn({
  variable: "--font-vazir",
  subsets: ["arabic"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {

  
  return (
    <html
      lang="fa"
      className={`${vazirmatn.variable}  h-full antialiased`}
    >
      <body className="">
       
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
